In [1]:
import numpy as np

In [8]:
# vector
a = np.array(3)
a.shape

()

In [9]:
# vector
b = np.array([1,2,3,4,5])
b.shape

(5,)

In [11]:
# matrix
c = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(c.shape)
c

(3, 5)


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [12]:
# tensor
d = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],
         [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],
         [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])
print(d.shape)
d

(3, 3, 5)


array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [17]:
d[0], d[1], d[2]

(array([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]),
 array([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]),
 array([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]))

In [19]:
d[0,1,2]

3

In [21]:
np.arange(1,51).reshape(5,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [23]:
# (start, end, 갯수)
np.linspace(1,10,10, endpoint=False) # endpoint=False 이면 end값을 포함하지 않는다.

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [24]:
np.logspace(-4, 3, 8)

array([1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

In [29]:
# shape
np.random.rand(5,5)

array([[0.94967951, 0.39790575, 0.61036767, 0.49895934, 0.00731536],
       [0.86636144, 0.4972434 , 0.48155319, 0.96800102, 0.79906495],
       [0.16444402, 0.03016801, 0.14760759, 0.47507796, 0.43792968],
       [0.82624315, 0.2661846 , 0.56260544, 0.62752389, 0.57061552],
       [0.75465718, 0.27859052, 0.18810992, 0.74831079, 0.13450697]])

In [33]:
np.random.randn(3,3)

array([[ 0.10096359,  0.34164321,  0.40037836],
       [-2.1301484 , -0.65070175, -0.0359969 ],
       [-0.67648009,  0.12339471,  2.35405334]])

In [30]:
# start, end, shape
np.random.randint(1, 10, (3,3))

array([[2, 9, 4],
       [8, 6, 9],
       [1, 4, 4]])

In [35]:
np.random.uniform(1, 10, (3,3))

array([[1.83984348, 8.34926013, 2.531413  ],
       [6.88697841, 2.47956174, 6.05722553],
       [8.7075255 , 4.87602643, 1.76955139]])

In [44]:
a = np.arange(1,11)

In [45]:
a.shape

(10,)

In [46]:
a[:, np.newaxis].shape

(10, 1)

In [48]:
a[np.newaxis,:].shape

(1, 10)

In [41]:
b=np.arange(1,26).reshape(-1,5)
b[1,2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
np.arange(1,51).reshape(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [50]:
np.sum(np.arange(1,51).reshape(5,10))

1275

In [51]:
np.arange(1,51).reshape(5,10).sum()

1275

In [53]:
np.arange(1,51).reshape(5,10).sum(axis=0)

array([105, 110, 115, 120, 125, 130, 135, 140, 145, 150])

In [54]:
np.arange(1,51).reshape(5,10).sum(axis=1)

array([ 55, 155, 255, 355, 455])

In [55]:
A = np.array([[[2,4,6,8],[7,6,3,4],[5,2,3,6]],
              [[4,3,2,1],[4,3,7,6],[8,10,7,8]]])
A.shape

(2, 3, 4)

In [56]:
A

array([[[ 2,  4,  6,  8],
        [ 7,  6,  3,  4],
        [ 5,  2,  3,  6]],

       [[ 4,  3,  2,  1],
        [ 4,  3,  7,  6],
        [ 8, 10,  7,  8]]])

In [57]:
A.sum(axis=0)

array([[ 6,  7,  8,  9],
       [11,  9, 10, 10],
       [13, 12, 10, 14]])

In [58]:
A.sum(axis=1)

array([[14, 12, 12, 18],
       [16, 16, 16, 15]])

In [59]:
A.sum(axis=2)

array([[20, 20, 16],
       [10, 20, 33]])

In [60]:
a = np.arange(1,10)

In [61]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a[2], a[6]

(3, 7)

In [67]:
a[[2,6]]

array([3, 7])

In [68]:
b = np.arange(1,26).reshape(5,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [70]:
b[1,2], b[3, 3]

(8, 19)

In [74]:
b[[1,3], [2,3]]

array([ 8, 19])

In [75]:
A = np.array([[[2,4,6,8],[7,6,3,4],[5,2,3,6]],
              [[4,3,2,1],[4,3,7,6],[8,10,7,8]]])
A

array([[[ 2,  4,  6,  8],
        [ 7,  6,  3,  4],
        [ 5,  2,  3,  6]],

       [[ 4,  3,  2,  1],
        [ 4,  3,  7,  6],
        [ 8, 10,  7,  8]]])

In [78]:
A[1, 1, 2], A[0, 1, 3], A[1, 2, 0]

(7, 4, 8)

In [79]:
A[[1,0,1], [1,1,2], [2,3,0]]

array([7, 4, 8])

In [86]:
np.array("2023-04-17", dtype=np.datetime64)

array('2023-04-17', dtype='datetime64[D]')

In [103]:
np.arange("2023-01-01", "2023-04-17",dtype="datetime64[M]")

array(['2023-01', '2023-02', '2023-03'], dtype='datetime64[M]')

In [ ]:
np.arange("2023-01-01", "2023-04-17",dtype="datetime64[M]")

In [104]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [105]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [108]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [113]:
np.hstack([a,b])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
np.vstack([a,b])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [119]:
a = np.arange(1,11).reshape(2,5)
b = np.arange(11,21).reshape(2,5)

In [120]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [121]:
b

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [122]:
np.c_[a,b]

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [123]:
np.r_[a,b]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [124]:
np.hstack([a,b])

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [125]:
np.vstack([a,b])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [129]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [128]:
a[a >= 3]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [130]:
x = np.arange(1,101)

np.random.choice(x, size = (3,4))

array([[57, 41, 93, 86],
       [53, 76, 29, 33],
       [55, 26, 32,  5]])